-- File generated by the BNF Converter (bnfc 2.9.6).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Omni.

module Omni.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Omni.Abs
import qualified Data.Text

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Omni.Abs.Ident where
  prt _ (Omni.Abs.Ident i) = doc $ showString (Data.Text.unpack i)
instance Print Omni.Abs.InfixOpIdent where
  prt _ (Omni.Abs.InfixOpIdent i) = doc $ showString (Data.Text.unpack i)
instance Print (Omni.Abs.Name' a) where
  prt i = \case
    Omni.Abs.Name _ id_ -> prPrec i 0 (concatD [prt 0 id_])

instance Print (Omni.Abs.Module' a) where
  prt i = \case
    Omni.Abs.Module _ name topdefs -> prPrec i 0 (concatD [doc (showString "module"), prt 0 name, doc (showString "("), doc (showString ")"), prt 0 topdefs])

instance Print (Omni.Abs.TopDef' a) where
  prt i = \case
    Omni.Abs.FnDef _ name paramlist type_ exp -> prPrec i 0 (concatD [prt 0 name, prt 0 paramlist, doc (showString ":"), prt 0 type_, doc (showString "="), prt 0 exp])

instance Print [Omni.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Omni.Abs.ParamList' a) where
  prt i = \case
    Omni.Abs.ParamList _ params -> prPrec i 0 (concatD [doc (showString "("), prt 0 params, doc (showString ")")])

instance Print (Omni.Abs.Param' a) where
  prt i = \case
    Omni.Abs.Param _ name type_ -> prPrec i 0 (concatD [prt 0 name, doc (showString ":"), prt 0 type_])

instance Print [Omni.Abs.Param' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Omni.Abs.Type' a) where
  prt i = \case
    Omni.Abs.TFn _ types type_ -> prPrec i 0 (concatD [doc (showString "("), prt 0 types, doc (showString ")"), doc (showString "->"), prt 0 type_])
    Omni.Abs.TUnit _ -> prPrec i 0 (concatD [doc (showString "("), doc (showString ")")])
    Omni.Abs.TInt _ -> prPrec i 0 (concatD [doc (showString "Int")])
    Omni.Abs.TNamed _ name -> prPrec i 0 (concatD [prt 0 name])

instance Print [Omni.Abs.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (Omni.Abs.Exp' a) where
  prt i = \case
    Omni.Abs.EIdent _ name -> prPrec i 1 (concatD [prt 0 name])
    Omni.Abs.EIntLit _ n -> prPrec i 1 (concatD [prt 0 n])
    Omni.Abs.EUnit _ -> prPrec i 1 (concatD [doc (showString "("), doc (showString ")")])
    Omni.Abs.EInfixOp _ exp1 infixopident exp2 -> prPrec i 0 (concatD [prt 0 exp1, prt 0 infixopident, prt 1 exp2])
    Omni.Abs.EApplication _ exp exps -> prPrec i 0 (concatD [prt 0 exp, doc (showString "("), prt 0 exps, doc (showString ")")])

instance Print [Omni.Abs.Exp' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
