name:                omni-parser
version:             0.1.0
license:             BSD-3-Clause
author:              Martin Jonsson
maintainer:          martinjonsson01@gmail.com
copyright:           2024 Martin Jonsson

dependencies:
- base
- text
- array


ghc-options:
- -Wno-all

library:
  source-dirs: src
