name:                omni-cli
version:             0.1.0
license:             BSD-3-Clause
author:              Martin Jonsson
maintainer:          martinjonsson01@gmail.com
copyright:           2024 Martin Jonsson

extra-source-files:
- README.md

dependencies:
- base
- rio
- omni-lib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  omnic:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - omni-cli
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
